// Code generated by "stringer -type=DiagnosticSeverity -trimprefix=Diagnostic"; DO NOT EDIT.

package providerops

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DiagnosticUnsupported-0]
	_ = x[DiagnosticWarning-1]
	_ = x[DiagnosticError-2]
}

const _DiagnosticSeverity_name = "UnsupportedWarningError"

var _DiagnosticSeverity_index = [...]uint8{0, 11, 18, 23}

func (i DiagnosticSeverity) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_DiagnosticSeverity_index)-1 {
		return "DiagnosticSeverity(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _DiagnosticSeverity_name[_DiagnosticSeverity_index[idx]:_DiagnosticSeverity_index[idx+1]]
}
