// Package mockutil contains some testing helpers intended to reduce boilerplate
// in tests that are using mocks generated by "mockgen".
//
// The main entrypoint is [Eq], which returns a [gomock.Matcher] that has a
// more permissive definition of equality than [gomock.Eq] when comparing
// cty values, cty types, protobuf messages, and some other types derived from
// those.
//
// The other functionality in here is all related to that mission, including
// [JSON] and [MsgPack] for concisely building expected JSON and MsgPack
// encodings of values, and [Diff] for diffing two values by the same rules
// that [Eq] uses so we can produce more detailed test failure messages.
package mockutil
