#!/bin/bash

# This is a small stub to help protoc run protoc-gen-go through "go tool" so
# it can find the version we selected in our go.mod.
exec go tool google.golang.org/protobuf/cmd/protoc-gen-go "$@"
