// Code generated by "stringer -type=AttributeUsage -trimprefix=Attribute"; DO NOT EDIT.

package providerschema

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[AttributeUsageUnsupported-0]
	_ = x[AttributeRequired-1]
	_ = x[AttributeOptional-2]
	_ = x[AttributeOptionalComputed-3]
	_ = x[AttributeComputed-4]
}

const _AttributeUsage_name = "UsageUnsupportedRequiredOptionalOptionalComputedComputed"

var _AttributeUsage_index = [...]uint8{0, 16, 24, 32, 48, 56}

func (i AttributeUsage) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_AttributeUsage_index)-1 {
		return "AttributeUsage(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _AttributeUsage_name[_AttributeUsage_index[idx]:_AttributeUsage_index[idx+1]]
}
