// Code generated by "stringer -type=DocStringFormat -trimprefix=DocString"; DO NOT EDIT.

package providerschema

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DocStringUnsupported-0]
	_ = x[DocStringPlain-1]
	_ = x[DocStringMarkdown-2]
}

const _DocStringFormat_name = "UnsupportedPlainMarkdown"

var _DocStringFormat_index = [...]uint8{0, 11, 16, 24}

func (i DocStringFormat) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_DocStringFormat_index)-1 {
		return "DocStringFormat(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _DocStringFormat_name[_DocStringFormat_index[idx]:_DocStringFormat_index[idx+1]]
}
