// Code generated by "stringer -type=NestingMode -trimprefix=Nesting"; DO NOT EDIT.

package providerschema

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NestingInvalid-0]
	_ = x[NestingSingle-1]
	_ = x[NestingList-2]
	_ = x[NestingSet-3]
	_ = x[NestingMap-4]
	_ = x[NestingGroup-5]
}

const _NestingMode_name = "InvalidSingleListSetMapGroup"

var _NestingMode_index = [...]uint8{0, 7, 13, 17, 20, 23, 28}

func (i NestingMode) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_NestingMode_index)-1 {
		return "NestingMode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _NestingMode_name[_NestingMode_index[idx]:_NestingMode_index[idx+1]]
}
